#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_ACCEL)			+= accel/

obj-$(CONFIG_COMPASS)		+= compass/

obj-$(CONFIG_GYRO)		+= gyro/

obj-$(CONFIG_LIGHT)		+= light/


